"""Test cases for Array & String problems (Category 01)."""

from . import TestCase, sorted_compare


ARRAY_STRING_TESTS = {
    "two_sum": [
        TestCase("simple case", (([2, 7, 11, 15], 9),), [0, 1], sorted_compare),
        TestCase("middle elements", (([3, 2, 4], 6),), [1, 2], sorted_compare),
        TestCase("duplicate values", (([3, 3], 6),), [0, 1], sorted_compare),
        TestCase("negative numbers", (([-1, -2, -3, -4, -5], -8),), [2, 4], sorted_compare),
        TestCase("mixed signs", (([-3, 4, 3, 90], 0),), [0, 2], sorted_compare),
        TestCase("zeros", (([0, 4, 3, 0], 0),), [0, 3], sorted_compare),
        TestCase("large numbers", (([1000000000, 2, 1000000000], 2000000000),), [0, 2], sorted_compare),
        TestCase("target at end", (([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 19),), [8, 9], sorted_compare),
        TestCase("negative target", (([5, -10, 3, -6], -16),), [1, 3], sorted_compare),
        TestCase("first and last", (([1, 5, 5, 5, 5, 5, 5, 5, 9], 10),), [0, 8], sorted_compare),
        TestCase("performance", ((list(range(100000)), 199997),), [99998, 99999], sorted_compare, is_performance=True, max_time=1.0),
    ],

    "valid_anagram": [
        TestCase("simple anagram", (("anagram", "nagaram"),), True),
        TestCase("not anagram", (("rat", "car"),), False),
        TestCase("same string", (("abc", "abc"),), True),
        TestCase("different lengths", (("ab", "abc"),), False),
        TestCase("empty strings", (("", ""),), True),
        TestCase("single char same", (("a", "a"),), True),
        TestCase("single char diff", (("a", "b"),), False),
        TestCase("repeated chars", (("aabb", "abab"),), True),
        TestCase("same letters diff count", (("aab", "abb"),), False),
        TestCase("unicode chars", (("日本語", "語日本"),), True),
        TestCase("long anagram", (("abcdefghijklmnopqrstuvwxyz" * 10, "zyxwvutsrqponmlkjihgfedcba" * 10),), True),
        TestCase("performance", (("abcdefghij" * 5000, "jihgfedcba" * 5000),), True, is_performance=True, max_time=1.0),
    ],

    "valid_palindrome": [
        TestCase("classic palindrome", (("A man, a plan, a canal: Panama",),), True),
        TestCase("not palindrome", (("race a car",),), False),
        TestCase("simple palindrome", (("aba",),), True),
        TestCase("even palindrome", (("abba",),), True),
        TestCase("empty after filter", ((" ",),), True),
        TestCase("single char", (("a",),), True),
        TestCase("only numbers", (("12321",),), True),
        TestCase("mixed case", (("Aa",),), True),
        TestCase("special chars only", ((",.!?",),), True),
        TestCase("numbers and letters", (("0P",),), False),
        TestCase("with colons", (("Was it a car or a cat I saw?",),), True),
        TestCase("empty string", (("",),), True),
    ],

    "reverse_string": [
        TestCase("simple", ((["h", "e", "l", "l", "o"],),), ["o", "l", "l", "e", "h"]),
        TestCase("even length", ((["H", "a", "n", "n", "a", "h"],),), ["h", "a", "n", "n", "a", "H"]),
        TestCase("single char", ((["a"],),), ["a"]),
        TestCase("two chars", ((["a", "b"],),), ["b", "a"]),
        TestCase("empty", (([],),), []),
        TestCase("palindrome", ((["r", "a", "c", "e", "c", "a", "r"],),), ["r", "a", "c", "e", "c", "a", "r"]),
        TestCase("numbers as chars", ((["1", "2", "3", "4"],),), ["4", "3", "2", "1"]),
        TestCase("special chars", ((["@", "#", "$"],),), ["$", "#", "@"]),
    ],

    "longest_common_prefix": [
        TestCase("common prefix", ((["flower", "flow", "flight"],),), "fl"),
        TestCase("no common prefix", ((["dog", "racecar", "car"],),), ""),
        TestCase("all same", ((["test", "test", "test"],),), "test"),
        TestCase("empty list", (([],),), ""),
        TestCase("single word", ((["alone"],),), "alone"),
        TestCase("empty string in list", ((["", "b", "c"],),), ""),
        TestCase("all empty", ((["", "", ""],),), ""),
        TestCase("single char prefix", ((["ab", "a"],),), "a"),
        TestCase("first is prefix", ((["abc", "abcd", "abcde"],),), "abc"),
        TestCase("last is prefix", ((["abcde", "abcd", "abc"],),), "abc"),
    ],

    "remove_duplicates": [
        TestCase("with duplicates", (([1, 1, 2],),), 2),
        TestCase("more duplicates", (([0, 0, 1, 1, 1, 2, 2, 3, 3, 4],),), 5),
        TestCase("no duplicates", (([1, 2, 3],),), 3),
        TestCase("all same", (([1, 1, 1, 1],),), 1),
        TestCase("empty", (([],),), 0),
        TestCase("single element", (([1],),), 1),
        TestCase("two same", (([2, 2],),), 1),
        TestCase("two different", (([1, 2],),), 2),
        TestCase("negative numbers", (([-3, -1, -1, 0, 0, 1, 2],),), 5),
        TestCase("large range", ((list(range(100)) + list(range(100)),),), 100),
    ],

    "rotate_array": [
        TestCase("rotate by 3", (([1, 2, 3, 4, 5, 6, 7], 3),), [5, 6, 7, 1, 2, 3, 4]),
        TestCase("rotate by 2", (([-1, -100, 3, 99], 2),), [3, 99, -1, -100]),
        TestCase("rotate by length", (([1, 2, 3], 3),), [1, 2, 3]),
        TestCase("rotate single", (([1], 1),), [1]),
        TestCase("rotate by zero", (([1, 2, 3], 0),), [1, 2, 3]),
        TestCase("rotate more than length", (([1, 2, 3], 4),), [3, 1, 2]),
        TestCase("rotate by 1", (([1, 2, 3, 4], 1),), [4, 1, 2, 3]),
        TestCase("double length", (([1, 2], 4),), [1, 2]),
        TestCase("large k", (([1, 2, 3, 4, 5], 102),), [4, 5, 1, 2, 3]),
    ],

    "move_zeroes": [
        TestCase("mixed", (([0, 1, 0, 3, 12],),), [1, 3, 12, 0, 0]),
        TestCase("single zero", (([0],),), [0]),
        TestCase("no zeros", (([1, 2, 3],),), [1, 2, 3]),
        TestCase("all zeros", (([0, 0, 0],),), [0, 0, 0]),
        TestCase("zeros at end", (([1, 2, 0, 0],),), [1, 2, 0, 0]),
        TestCase("zeros at start", (([0, 0, 1, 2],),), [1, 2, 0, 0]),
        TestCase("alternating", (([0, 1, 0, 2, 0, 3],),), [1, 2, 3, 0, 0, 0]),
        TestCase("empty", (([],),), []),
        TestCase("single non-zero", (([1],),), [1]),
        TestCase("many zeros", (([0, 0, 0, 0, 1],),), [1, 0, 0, 0, 0]),
    ],

    "plus_one": [
        TestCase("simple", (([1, 2, 3],),), [1, 2, 4]),
        TestCase("carry", (([9],),), [1, 0]),
        TestCase("multiple carry", (([9, 9, 9],),), [1, 0, 0, 0]),
        TestCase("no carry", (([1, 2, 9],),), [1, 3, 0]),
        TestCase("single digit", (([0],),), [1]),
        TestCase("middle carry", (([1, 9, 9],),), [2, 0, 0]),
        TestCase("large number", (([9, 8, 7, 6, 5, 4, 3, 2, 1, 0],),), [9, 8, 7, 6, 5, 4, 3, 2, 1, 1]),
        TestCase("partial carry", (([2, 9, 9],),), [3, 0, 0]),
        TestCase("no carry large", (([1, 2, 3, 4, 5, 6, 7, 8],),), [1, 2, 3, 4, 5, 6, 7, 9]),
    ],

    "merge_sorted_arrays": [
        TestCase("simple merge", (([1, 2, 3, 0, 0, 0], 3, [2, 5, 6], 3),), [1, 2, 2, 3, 5, 6]),
        TestCase("empty second", (([1], 1, [], 0),), [1]),
        TestCase("empty first", (([0], 0, [1], 1),), [1]),
        TestCase("all from second", (([0, 0, 0], 0, [1, 2, 3], 3),), [1, 2, 3]),
        TestCase("interleaved", (([1, 3, 5, 0, 0, 0], 3, [2, 4, 6], 3),), [1, 2, 3, 4, 5, 6]),
        TestCase("second all smaller", (([4, 5, 6, 0, 0, 0], 3, [1, 2, 3], 3),), [1, 2, 3, 4, 5, 6]),
        TestCase("with duplicates", (([1, 2, 3, 0, 0, 0], 3, [1, 2, 3], 3),), [1, 1, 2, 2, 3, 3]),
        TestCase("negative numbers", (([-3, -1, 0, 0, 0], 2, [-2, 1, 2], 3),), [-3, -2, -1, 1, 2]),
    ],

    "product_except_self": [
        TestCase("simple", (([1, 2, 3, 4],),), [24, 12, 8, 6]),
        TestCase("with zero", (([-1, 1, 0, -3, 3],),), [0, 0, 9, 0, 0]),
        TestCase("two elements", (([1, 2],),), [2, 1]),
        TestCase("with negative", (([-1, -2, -3],),), [6, 3, 2]),
        TestCase("two zeros", (([0, 0, 1],),), [0, 0, 0]),
        TestCase("all ones", (([1, 1, 1, 1],),), [1, 1, 1, 1]),
        TestCase("single zero", (([1, 2, 0, 4],),), [0, 0, 8, 0]),
        TestCase("large values", (([10, 20, 30],),), [600, 300, 200]),
    ],

    "container_with_most_water": [
        TestCase("example 1", (([1, 8, 6, 2, 5, 4, 8, 3, 7],),), 49),
        TestCase("example 2", (([1, 1],),), 1),
        TestCase("decreasing", (([4, 3, 2, 1, 4],),), 16),
        TestCase("increasing", (([1, 2, 3, 4, 5],),), 6),
        TestCase("peak in middle", (([1, 2, 4, 3],),), 4),
        TestCase("same height", (([5, 5, 5, 5],),), 15),
        TestCase("tall ends", (([10, 1, 1, 1, 10],),), 40),
        TestCase("short middle", (([5, 1, 5],),), 10),
    ],

    "trapping_rain_water": [
        TestCase("example 1", (([0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1],),), 6),
        TestCase("example 2", (([4, 2, 0, 3, 2, 5],),), 9),
        TestCase("no water", (([1, 2, 3],),), 0),
        TestCase("descending", (([5, 4, 3, 2, 1],),), 0),
        TestCase("single bar", (([5],),), 0),
        TestCase("two bars", (([1, 2],),), 0),
        TestCase("valley", (([3, 0, 3],),), 3),
        TestCase("empty", (([],),), 0),
        TestCase("flat", (([3, 3, 3, 3],),), 0),
        TestCase("w shape", (([3, 0, 2, 0, 3],),), 7),
    ],

    "longest_substring_without_repeating": [
        TestCase("abcabcbb", (("abcabcbb",),), 3),
        TestCase("bbbbb", (("bbbbb",),), 1),
        TestCase("pwwkew", (("pwwkew",),), 3),
        TestCase("empty", (("",),), 0),
        TestCase("single char", (("a",),), 1),
        TestCase("all unique", (("abcdef",),), 6),
        TestCase("two chars alternating", (("abababab",),), 2),
        TestCase("space in string", (("hello world",),), 6),
        TestCase("special chars", (("a!b@c#d",),), 7),
        TestCase("numbers", (("12312345",),), 5),
    ],

    "minimum_window_substring": [
        TestCase("example 1", (("ADOBECODEBANC", "ABC"),), "BANC"),
        TestCase("example 2", (("a", "a"),), "a"),
        TestCase("no window", (("a", "aa"),), ""),
        TestCase("exact match", (("abc", "abc"),), "abc"),
        TestCase("t larger", (("a", "b"),), ""),
        TestCase("duplicate chars in t", (("aa", "aa"),), "aa"),
        TestCase("window at start", (("ABCD", "AB"),), "AB"),
        TestCase("window at end", (("DCBA", "BA"),), "BA"),
        TestCase("case sensitive", (("AaBb", "ab"),), "aBb"),
    ],
}
